/* Aurum Luxe — catalogue.
   Hard rule: MAX_BUDGET is the ceiling for this store. No single item and no
   order total may exceed it. Prices are in INR (paise-free, whole rupees). */

const MAX_BUDGET = 1000000; // ₹10,00,000

const CATEGORIES = [
  { id: 'all',      label: 'All' },
  { id: 'tech',     label: 'Technology' },
  { id: 'watches',  label: 'Watches' },
  { id: 'apparel',  label: 'Apparel' },
  { id: 'leather',  label: 'Leather Goods' },
  { id: 'audio',    label: 'Audio' },
  { id: 'jewellery',label: 'Jewellery' },
  { id: 'home',     label: 'Objets' }
];

const PRODUCTS = [
  { id:'t1', cat:'tech', name:'Aurum Fold Ultra', brand:'AURUM', price:249000,
    blurb:'Titanium-hinged foldable with a hand-polished ceramic back.',
    detail:'A 7.9″ folding display under sapphire-hardened glass, framed in grade-5 titanium. Finished by hand over eleven stages.',
    specs:{ 'Display':'7.9″ LTPO Fold', 'Frame':'Grade-5 Titanium', 'Storage':'1 TB', 'Finish':'Ceramic Noir' },
    tone:['#1c1c22','#3a3f4b'], mark:'◧', stock:6 },
  { id:'t2', cat:'tech', name:'Studio 16 Carbon', brand:'MERIDIAN', price:489000,
    blurb:'Forged-carbon workstation laptop, 128 GB unified memory.',
    detail:'A forged-carbon chassis milled from a single billet, with a colour-calibrated mini-LED panel for reference-grade work.',
    specs:{ 'Display':'16″ mini-LED XDR', 'Memory':'128 GB unified', 'Storage':'4 TB NVMe', 'Weight':'1.6 kg' },
    tone:['#23252b','#4b5058'], mark:'▤', stock:4 },
  { id:'t3', cat:'tech', name:'Halo Lens Pro', brand:'AURUM', price:365000,
    blurb:'Spatial headset with micro-OLED optics and a woven titanium band.',
    detail:'Dual 4K micro-OLED panels, pancake optics and a hand-woven band that redistributes weight across the crown.',
    specs:{ 'Optics':'Dual 4K micro-OLED', 'Field':'112°', 'Band':'Woven Titanium', 'Runtime':'4 hrs' },
    tone:['#2b2438','#59486f'], mark:'◎', stock:5 },
  { id:'t4', cat:'tech', name:'Solstice 8K Cinema', brand:'MERIDIAN', price:720000,
    blurb:'85″ 8K micro-LED panel on a cast-bronze pedestal.',
    detail:'Micro-LED at 8K with per-pixel dimming, mounted on a cast-bronze pedestal that hides every cable run.',
    specs:{ 'Panel':'85″ micro-LED 8K', 'Peak':'4000 nits', 'Stand':'Cast Bronze', 'Audio':'11.2.4' },
    tone:['#12161c','#2f3d4d'], mark:'▭', stock:2 },

  { id:'w1', cat:'watches', name:'Chronomètre Noir', brand:'VALLÉE', price:875000,
    blurb:'Hand-wound chronometer, 72-hour reserve, black-polished bridges.',
    detail:'A hand-wound calibre finished in the Vallée tradition: black-polished bridges, chamfered by hand, 72-hour reserve.',
    specs:{ 'Calibre':'VL-31 hand-wound', 'Reserve':'72 hours', 'Case':'39 mm Platinum', 'Dial':'Grand Feu Enamel' },
    tone:['#1a1a1d','#4a4438'], mark:'◷', stock:1 },
  { id:'w2', cat:'watches', name:'Skeleton Tourbillon 41', brand:'VALLÉE', price:960000,
    blurb:'Flying tourbillon under a fully skeletonised sapphire dial.',
    detail:'A flying tourbillon suspended beneath sapphire, with a movement openworked to 38% of its original mass.',
    specs:{ 'Complication':'Flying Tourbillon', 'Case':'41 mm Rose Gold', 'Glass':'Double Sapphire', 'Reserve':'80 hours' },
    tone:['#241d18','#6b5230'], mark:'✧', stock:1 },
  { id:'w3', cat:'watches', name:'Diver Abyss 300', brand:'ORSA', price:298000,
    blurb:'300 m steel diver with a ceramic bezel and forged-blue dial.',
    detail:'Rated to 300 metres, with a lume-filled ceramic bezel and a dial forged to hold depth like open water.',
    specs:{ 'Depth':'300 m', 'Case':'42 mm Steel', 'Bezel':'Ceramic', 'Movement':'Automatic COSC' },
    tone:['#0f2233','#20536f'], mark:'⏱', stock:8 },

  { id:'a1', cat:'apparel', name:'Vicuña Overcoat', brand:'SARTO MILANO', price:640000,
    blurb:'Undyed vicuña, canvassed by hand over eighty hours.',
    detail:'Woven from undyed vicuña — the rarest fibre in tailoring — and canvassed entirely by hand across eighty hours.',
    specs:{ 'Fibre':'100% Vicuña', 'Construction':'Full canvas', 'Lining':'Silk twill', 'Origin':'Milano' },
    tone:['#3a2f26','#8a7358'], mark:'❦', stock:3 },
  { id:'a2', cat:'apparel', name:'Cashmere Tuxedo', brand:'SARTO MILANO', price:385000,
    blurb:'Midnight-blue cashmere dinner suit with grosgrain facings.',
    detail:'Midnight blue reads blacker than black under evening light. Grosgrain facings, hand-set sleeves, working cuffs.',
    specs:{ 'Fibre':'Cashmere 15.5μ', 'Facing':'Silk grosgrain', 'Fit':'Made-to-measure', 'Buttons':'Horn' },
    tone:['#151a2b','#333e63'], mark:'♦', stock:5 },
  { id:'a3', cat:'apparel', name:'Silk Opera Gown', brand:'MAISON RÊVE', price:520000,
    blurb:'Bias-cut duchesse silk with 4,000 hand-set crystals.',
    detail:'Cut on the bias from duchesse silk and set with four thousand crystals across three weeks of atelier work.',
    specs:{ 'Fabric':'Duchesse silk', 'Embellishment':'4,000 crystals', 'Atelier hours':'190', 'Closure':'Hand-stitched' },
    tone:['#2c1524','#7a3355'], mark:'✦', stock:2 },
  { id:'a4', cat:'apparel', name:'Shearling Aviator', brand:'ORSA', price:195000,
    blurb:'Toscana shearling, vegetable-tanned and hand-finished.',
    detail:'Toscana shearling, vegetable-tanned over six weeks, with a shell that softens to the wearer within a season.',
    specs:{ 'Material':'Toscana shearling', 'Tanning':'Vegetable, 6 wks', 'Hardware':'Solid brass', 'Lining':'Natural wool' },
    tone:['#33251a','#8f6a42'], mark:'▲', stock:6 },

  { id:'l1', cat:'leather', name:'Crocodile Weekender', brand:'HOUSE OF KANE', price:915000,
    blurb:'Single-artisan Porosus crocodile travel bag, palladium fittings.',
    detail:'Built end to end by one artisan from matched Porosus crocodile, with palladium fittings and a saddle-stitched frame.',
    specs:{ 'Leather':'Porosus crocodile', 'Hardware':'Palladium', 'Stitch':'Saddle, by hand', 'Maker':'Single artisan' },
    tone:['#1e2a20','#4d7052'], mark:'▬', stock:1 },
  { id:'l2', cat:'leather', name:'Box-Calf Attaché', brand:'HOUSE OF KANE', price:275000,
    blurb:'Mirror-finished box calf with a suede-lined document well.',
    detail:'Mirror-finished box calf over a rigid frame, with a suede-lined well sized for A4 without creasing.',
    specs:{ 'Leather':'Box calf', 'Lining':'Alcantara', 'Lock':'Combination brass', 'Capacity':'A4 + 16″' },
    tone:['#241a16','#66463a'], mark:'▮', stock:4 },
  { id:'l3', cat:'leather', name:'Alligator Belt & Buckle', brand:'HOUSE OF KANE', price:98000,
    blurb:'Matte alligator strap with a solid white-gold buckle.',
    detail:'A matte alligator strap cut from a single belly, finished with a solid white-gold buckle.',
    specs:{ 'Leather':'Alligator belly', 'Buckle':'18k White gold', 'Width':'32 mm', 'Edges':'Hand-painted' },
    tone:['#20221c','#585c3f'], mark:'━', stock:9 },

  { id:'s1', cat:'audio', name:'Aria Reference Speakers', brand:'CANTUS', price:880000,
    blurb:'Beryllium-tweeter floorstanders in lacquered walnut. Pair.',
    detail:'A matched pair of floorstanders with beryllium tweeters, in a walnut cabinet given eighteen coats of lacquer.',
    specs:{ 'Tweeter':'Beryllium dome', 'Cabinet':'Walnut, 18 coats', 'Response':'22 Hz – 40 kHz', 'Sold as':'Matched pair' },
    tone:['#2a1f18','#7d5433'], mark:'◍', stock:2 },
  { id:'s2', cat:'audio', name:'Obsidian Turntable', brand:'CANTUS', price:445000,
    blurb:'Magnetically levitated platter on a granite plinth.',
    detail:'A magnetically levitated platter over a granite plinth — no bearing, no rumble, no contact.',
    specs:{ 'Platter':'Maglev, 8 kg', 'Plinth':'Black granite', 'Arm':'Carbon unipivot', 'Wow & flutter':'0.008%' },
    tone:['#16181b','#3e4750'], mark:'◉', stock:3 },
  { id:'s3', cat:'audio', name:'Solitaire Headphones', brand:'CANTUS', price:165000,
    blurb:'Electrostatic reference headphones with a leather-clad amp.',
    detail:'Electrostatic drivers paired with a dedicated valve energiser, clad in the same leather as the earcups.',
    specs:{ 'Driver':'Electrostatic', 'Amp':'Valve energiser', 'Cups':'Nappa leather', 'Impedance':'N/A (stat)' },
    tone:['#1b1d26','#464e6b'], mark:'⌇', stock:7 },

  { id:'j1', cat:'jewellery', name:'Emerald Solitaire Ring', brand:'VERDANT', price:790000,
    blurb:'3.1 ct Colombian emerald, platinum six-claw setting.',
    detail:'A 3.1 ct Colombian emerald of vivid saturation, held in a platinum six-claw setting that lets light through the pavilion.',
    specs:{ 'Stone':'3.1 ct Colombian emerald', 'Setting':'Platinum 950', 'Cut':'Emerald', 'Certificate':'Included' },
    tone:['#0e2a22','#1f7a5c'], mark:'◆', stock:1 },
  { id:'j2', cat:'jewellery', name:'Sautoir de Perles', brand:'VERDANT', price:340000,
    blurb:'Akoya pearl sautoir, hand-knotted on silk, gold clasp.',
    detail:'Graduated Akoya pearls, hand-knotted on silk between each bead, closing on an 18k gold clasp.',
    specs:{ 'Pearls':'Akoya, graduated', 'Length':'92 cm', 'Knotting':'Silk, by hand', 'Clasp':'18k Gold' },
    tone:['#2a2530','#8d8195'], mark:'◌', stock:3 },
  { id:'j3', cat:'jewellery', name:'Onyx Cufflinks', brand:'VERDANT', price:72000,
    blurb:'Black onyx set in rose gold, with a whale-back fitting.',
    detail:'Domed black onyx set in rose gold, on a whale-back fitting weighted to sit flat through a long evening.',
    specs:{ 'Stone':'Black onyx', 'Metal':'18k Rose gold', 'Fitting':'Whale-back', 'Case':'Leather, included' },
    tone:['#221a1c','#6d4a45'], mark:'❖', stock:12 },

  { id:'h1', cat:'home', name:'Meridian Globe', brand:'ATELIER NORD', price:410000,
    blurb:'Hand-gilded globe on a bronze meridian, semi-precious inlay.',
    detail:'Continents inlaid in semi-precious stone and hand-gilded, rotating within a cast-bronze meridian ring.',
    specs:{ 'Diameter':'50 cm', 'Inlay':'Lapis, malachite, onyx', 'Ring':'Cast bronze', 'Edition':'of 25' },
    tone:['#132030','#2c6480'], mark:'◐', stock:2 },
  { id:'h2', cat:'home', name:'Fountain Pen No. 1', brand:'ATELIER NORD', price:145000,
    blurb:'Urushi lacquer over ebonite, solid gold nib, of 100.',
    detail:'Forty layers of urushi lacquer over an ebonite body, with a solid gold nib tuned by hand before dispatch.',
    specs:{ 'Body':'Urushi over ebonite', 'Nib':'18k Gold, hand-tuned', 'Filling':'Piston', 'Edition':'of 100' },
    tone:['#2b1416','#7c2f2c'], mark:'✎', stock:5 },
  { id:'h3', cat:'home', name:'Crystal Decanter Set', brand:'ATELIER NORD', price:88000,
    blurb:'Hand-cut lead crystal decanter with six matched glasses.',
    detail:'Hand-cut lead crystal, mouth-blown, with six matched glasses that ring true when struck.',
    specs:{ 'Material':'Lead crystal', 'Pieces':'1 decanter + 6', 'Method':'Mouth-blown', 'Cut':'By hand' },
    tone:['#1c2226','#5b7480'], mark:'⬡', stock:6 }
];

PRODUCTS.forEach(p => {
  if (p.price > MAX_BUDGET) throw new Error(`${p.name} exceeds the store ceiling.`);
});
